name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8'

      - name: Restore dependencies
        run: dotnet restore LambdaApiCICD/LambdaApiCICD.csproj

      - name: Run tests (optional)
        run: |
          echo "Running tests (if any)..."
          dotnet test --no-build --verbosity normal || echo "No tests found or test project missing – continuing."

      - name: Publish Lambda project
        run: dotnet publish LambdaApiCICD/LambdaApiCICD.csproj -c Release -o ./publish --self-contained false

      - name: Zip publish folder
        run: |
          cd publish
          zip -r ../lambda.zip .

      - name: Upload to AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          inline: |
            aws lambda update-function-code \
              --function-name LambdaApiCICD \
              --zip-file fileb://lambda.zip
